name: myBlog
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
      REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup environment variables
        run: |
            echo "CLOUD_AWS_CREDENTIALS_ACCESS_KEY=$ACCESS_KEY" >> $GITHUB_ENV
            echo "CLOUD_AWS_CREDENTIALS_SECRET_KEY=$SECRET_KEY" >> $GITHUB_ENV
            echo "CLOUD_AWS_S3_BUCKET=$BUCKET_NAME" >> $GITHUB_ENV
            echo "CLOUD_AWS_REGION_STATIC=$REGION" >> $GITHUB_ENV
      - name: set current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Show Current Time
        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"
