name: myBlog
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_VAR:${{secrets.MYENV}}

    steps:
      - name: gitclone form CIserver to github Repository
        run: echo "wjdalsrdwq  $MY_VAR"
#        uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: 17
#          distribution: temurin
#      - name: Grant execute permission for gradlew
#        run: chmod +x ./gradlew
#        shell: bash
#      - name: Build with Gradle
#        run: ./gradlew clean build
#        shell: bash
#      - name: Get current time
#        uses: 1466587594/get-current-time@v2
#        id: current-time
#        with:
#          format: YYYY-MM-DDTHH-mm-ss
#          utcOffset: "+09:00"
#      - name: Show Current Time
#        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"

