name: myBlog
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
      REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup application properties
        run: |
            echo "cloud.aws.credentials.access-key=$ACCESS_KEY" >> $GITHUB_ENV
            echo "cloud.aws.credentials.secret-key=$SECRET_KEY" >> $GITHUB_ENV
            echo "cloud.aws.s3.bucket=$BUCKET_NAME" >> $GITHUB_ENV
            echo "cloud.aws.region.static=$REGION" >> $GITHUB_ENV
      - name: set current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Show Current Time
        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"
