name: myBlog
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_VAR: ${{ secrets.MYENV }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print environment variable
        run: echo "wjdalsrlaa$MY_VAR"

