name: myBlog
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
      REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup environment variables
        run: echo "$REGION"

